
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jul 28 16:07:03 CST 2020
//----------------------------------------------------

package binarioadecimal.cup;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int BIN = 3;
  public static final int PUNTO = 2;
  public static final int ERROR = 4;
  public static final int error = 1;
  public static final int EOF = 0;
}

